### ISSUE TITLE
Add Random Quote Machine Project

### ISSUE THREAD

**Issue by Airscripts** [Airscripts/campfire#18]
**Is your feature request related to a problem? Please describe.**
As of now I have a repository for every project into freeCodeCamp's curriculum that I want into one single repository.  

**Describe the solution you'd like**
Merge the related repository into campfire.  
The repository can be found here: https://github.com/Airscripts/fcc-random-quote-machine.

**Describe alternatives you've considered**
/

**Additional context**
How to do it correctly:
1. Fork this project and then clone the repository on your machine;
2. Run the following commands in sequence:
```bash
cd campfire
git pull origin main
git remote add -f project-name link-to-project
git switch -c new-branch-name
git merge project-name/master --allow-unrelated-histories
git rebase -i main
```
3. Move the merged project into campfire/curriculum/front-end-development-libraries;
4. Commit changes;
5. Push and open pull request.

**Comment by strawHat121** [comment]
Can I take this ?

**Comment by Airscripts** [comment]
For sure @strawHat121! 
Do you need any help with it?

**Comment by strawHat121** [comment]
No I dont think so.

You already have the code in a different repo.

I assume you just need it to be moved into this main one ?

**Comment by Airscripts** [comment]
> No I dont think so.
> 
> You already have the code in a different repo.
> 
> I assume you just need it to be moved into this main one ?

Yes, but you have to **merge the git histories**.  
You can do this by adding a remote to the repository that you've chosen and run a ```git merge``` command into campfire.  
After this, just move the project into the right curriculum location.

**Comment by Airscripts** [comment]
I've added additional context to the issue in case is needed.
Let me know if you need something!

**Comment by mattskinosix** [comment]
Can I take this??

**Comment by mateonunez** [comment]
Hey @Airscripts it looks really easy, can I work on this?

**Comment by elgorditosalsero** [comment]
Yo!

May I take this one or you need help for other?

Ty @Airscripts

**Comment by GuidoPenta** [comment]
I can help too!

**Comment by paolapog** [comment]
👋🏻! 
Can I help too? Ty :)

**Comment by Airscripts** [comment]
I don't know what is going on here but the issue is assigned to @strawHat121.
If he doesn't show up by tomorrow we can decide who can take it!

**Comment by pannyloo** [comment]
I mean.. do you maybe need help with this?

**Comment by Airscripts** [comment]
I've picked the issue back up @strawHat121.  
If anyone wants to do it, just open a pull request. 😊
