### ISSUE TITLE
Add Clock Project

### ISSUE THREAD

**Issue by Airscripts** [Airscripts/campfire#20]
**Is your feature request related to a problem? Please describe.**
As of now I have a repository for every project into freeCodeCamp's curriculum that I want into one single repository.  

**Describe the solution you'd like**
Merge the related repository into campfire.  
The repository can be found here: https://github.com/Airscripts/fcc-clock.

**Describe alternatives you've considered**
/

**Additional context**
How to do it correctly:
1. Fork this project and then clone the repository on your machine;
2. Run the following commands in sequence:
```bash
cd campfire
git pull origin main
git remote add -f project-name link-to-project
git switch -c new-branch-name
git merge project-name/main --allow-unrelated-histories
git rebase -i main
```
3. Move the merged project into campfire/curriculum/front-end-development-libraries;
4. Commit changes;
5. Push and open pull request.

**Comment by elgorditosalsero** [comment]
Yo

This command is wrong for `fcc-clock` as is not

```git merge project-name/master --allow-unrelated-histories```

but

```git merge project-name/main --allow-unrelated-histories```
